spring:
  profiles:
   active:
   - dev
---
server:
  port: 6002
spring:
  profiles: dev  #开发环境
  application:
   name: microservicecloud-config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 6002
spring:
  profiles: test  #测试环境
  application:
   name: microservicecloud-config-client-refreshabc
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-config-6002   # 在eureka中显示对应的服务名字
    prefer-ip-address: true     #在eureka中下边的访问路径可以显示IP地址
